//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QnALoader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QnALoader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BR04
        ///CEP01
        ///CEP03
        ///CON01
        ///CON02
        ///CON03
        ///CON04
        ///CON05
        ///CON06
        ///CON07
        ///CON08
        ///DP01
        ///DP02
        ///DP13
        ///DP15
        ///DP18
        ///DP22
        ///DP23
        ///DP28
        ///DP29
        ///DP30
        ///DP42
        ///DP43
        ///DP50
        ///DP60
        ///DP68
        ///DP71
        ///DP72
        ///DP73
        ///DP74
        ///DP75
        ///DP76
        ///DP78
        ///DP79
        ///DP81
        ///DP82
        ///DP83
        ///DP84
        ///DP85
        ///DVA03
        ///DVA06
        ///DVA19
        ///DVA21
        ///DVA23
        ///F111-01
        ///F111-02
        ///F111-03
        ///F111-04
        ///F111-05
        ///F111-07
        ///F111-09
        ///FIP01
        ///FIP02
        ///FIP04
        ///GS01
        ///GS02
        ///GS03
        ///GS04
        ///GS05
        ///HAC01
        ///HAC02
        ///HCS01
        ///HCS05
        ///HCS10
        ///HIP01
        ///HIP06
        ///HIP40
        ///HIP72
        ///HIP80
        ///HIP90
        ///HSV01
        ///HSV02
        ///HSV03
        ///HSV05
        ///HSV06
        ///HSV10
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string factSheetIdList {
            get {
                return ResourceManager.GetString("factSheetIdList", resourceCulture);
            }
        }
    }
}
