//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchTests.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SearchTests.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;title&quot;: &quot;Factsheet IS75 - Renting and Rent Assistance – Social Security Age Pensioners&quot;,
        ///    &quot;keywordsFromIndexPage&quot;: [
        ///      &quot;Accommodation&quot;,
        ///      &quot;Address&quot;,
        ///      &quot;Age pension&quot;,
        ///      &quot;Allowances&quot;,
        ///      &quot;Benefits&quot;,
        ///      &quot;Eligibility&quot;,
        ///      &quot;Rent&quot;,
        ///      &quot;Residential Circumstances&quot;
        ///    ],
        ///    &quot;factSheetHtml&quot;: &quot;&lt;div class=\&quot;region region-content\&quot;&gt;\n    &lt;div id=\&quot;block-system-main\&quot; class=\&quot;block block-system first odd\&quot;&gt;\n\n    \n  &lt;div class=\&quot;content\&quot;&gt;\n    &lt;article class=\&quot;node-1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testJson {
            get {
                return ResourceManager.GetString("testJson", resourceCulture);
            }
        }
    }
}
